# Generated by Django 3.1.2 on 2020-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=8)),
                ('u_age', models.IntegerField(default=1)),
                ('u_account_number', models.CharField(max_length=16)),
                ('u_password', models.CharField(max_length=12)),
            ],
        ),
    ]
