# Generated by Django 3.1.2 on 2020-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='u_lv',
            field=models.IntegerField(default=0),
        ),
    ]
