# Generated by Django 3.1.2 on 2020-10-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_users_u_lv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='u_lv',
        ),
    ]
